---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/docker/

# my-docker:
#   host: 127.0.0.1
#   port: 2375

# my-docker:
#   socket: /var/run/docker.sock

arrstack:
  host: http://{{HOMEPAGE_VAR_ARR_MACHINE}}
  port: 2222

gameservers:
  host: http://{{HOMEPAGE_VAR_GAMESERVERS_MACHINE}}
  port: 2222

mainvm:
  host: http://{{HOMEPAGE_VAR_MAINVM_MACHINE}}
  port: 2222
