---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Machine stats:
    - MainVM:
        - CPU:
            widget:
              type: glances
              url: {{HOMEPAGE_VAR_GLANCES_MAINVM_URL}}
              username: {{HOMEPAGE_VAR_GLANCES_USERNAME}}
              password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}}
              metric: cpu
              version: 4
        - Memory:
            widget:
              type: glances
              url: {{HOMEPAGE_VAR_GLANCES_MAINVM_URL}}
              username: {{HOMEPAGE_VAR_GLANCES_USERNAME}}
              password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}}
              metric: memory
              version: 4
        - Network:
            widget:
              type: glances
              url: {{HOMEPAGE_VAR_GLANCES_MAINVM_URL}}
              username: {{HOMEPAGE_VAR_GLANCES_USERNAME}}
              password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}}
              metric: network:ens18
              version: 4
        - Disk usage:
            widget:
              type: glances
              url: {{HOMEPAGE_VAR_GLANCES_MAINVM_URL}}
              username: {{HOMEPAGE_VAR_GLANCES_USERNAME}}
              password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}}
              metric: fs:/hostfs
              version: 4
    - Arr:
        - CPU:
            widget:
              type: glances
              url: {{HOMEPAGE_VAR_GLANCES_ARR_URL}}
              username: {{HOMEPAGE_VAR_GLANCES_USERNAME}}
              password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}}
              metric: cpu
              version: 4
        - Memory:
            widget:
              type: glances
              url: {{HOMEPAGE_VAR_GLANCES_ARR_URL}}
              username: {{HOMEPAGE_VAR_GLANCES_USERNAME}}
              password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}}
              metric: memory
              version: 4
        - Network:
            widget:
              type: glances
              url: {{HOMEPAGE_VAR_GLANCES_ARR_URL}}
              username: {{HOMEPAGE_VAR_GLANCES_USERNAME}}
              password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}}
              metric: network:ens18
              version: 4
        - Disk usage:
            widget:
              type: glances
              url: {{HOMEPAGE_VAR_GLANCES_ARR_URL}}
              username: {{HOMEPAGE_VAR_GLANCES_USERNAME}}
              password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}}
              metric: fs:/hostfs
              version: 4
    - GameServers:
        - CPU:
            widget:
              type: glances
              url: {{HOMEPAGE_VAR_GLANCES_GAMESERVERS_URL}}
              username: {{HOMEPAGE_VAR_GLANCES_USERNAME}}
              password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}}
              metric: cpu
              version: 4
        - Memory:
            widget:
              type: glances
              url: {{HOMEPAGE_VAR_GLANCES_GAMESERVERS_URL}}
              username: {{HOMEPAGE_VAR_GLANCES_USERNAME}}
              password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}}
              metric: memory
              version: 4
        - Network:
            widget:
              type: glances
              url: {{HOMEPAGE_VAR_GLANCES_GAMESERVERS_URL}}
              username: {{HOMEPAGE_VAR_GLANCES_USERNAME}}
              password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}}
              metric: network:ens18
              version: 4
        - Disk usage:
            widget:
              type: glances
              url: {{HOMEPAGE_VAR_GLANCES_GAMESERVERS_URL}}
              username: {{HOMEPAGE_VAR_GLANCES_USERNAME}}
              password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}}
              metric: fs:/hostfs
              version: 4
