---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Tom's Lab
description: Tom is the best
theme: dark
color: stone

layout:
  Machine stats:
    Arr:
      style: row
      columns: 4
    MainVM:
      style: row
      columns: 4
    GameServers:
      style: row
      columns: 4
