---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- glances:
    url: http://192.168.0.65:61208
    username: {{HOMEPAGE_VAR_GLANCES_USERNAME}}
    password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}}
    label: mainVM
    version: 4
    uptime: true
    cpu: false
    mem: false

- glances:
    url: http://192.168.0.197:61208
    username: {{HOMEPAGE_VAR_GLANCES_USERNAME}}
    password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}}
    label: arrStack
    version: 4
    uptime: true
    cpu: false
    mem: false

- glances:
    url: http://192.168.0.37:61208
    username: {{HOMEPAGE_VAR_GLANCES_USERNAME}}
    password: {{HOMEPAGE_VAR_GLANCES_PASSWORD}}
    label: gameServers
    version: 4
    uptime: true
    cpu: false
    mem: false
